spring.application.name=backend

server.port=8089
# spring.datasource.url=jdbc:postgresql://localhost:5433/grocio_db
spring.datasource.url==jdbc:postgresql://db.hflaslvmhqfoyjyjyxou.supabase.co:5432/postgres?user=postgres&password=[YOUR-PASSWORD]
spring.datasource.username=postgres
spring.datasource.password=iRulemynumber#375truck
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true