spring.application.name=backend

server.port=8089
# spring.datasource.url=jdbc:postgresql://localhost:5433/grocio_db
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.hflaslvmhqfoyjyjyxou
spring.datasource.password=iRulemynumber#375truck
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.open-in-view=false

spring.jackson.time-zone=UTC

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


razorpay.key-id=rzp_test_T3yG011WzUWaqf
razorpay.key-secret=GnU809KEBL22UHjaebUAxfdm

# JWT Configuration
jwt.secret=Qx7vL9nM2pR5sT8uW1yZ4aBcDeFgHiJkLmNoPqRsTuVwXyZ1234567890AbCdEfGh
jwt.expiration=36000000

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.connection-timeout=30000

spring.datasource.hikari.leak-detection-threshold=10000